# Generated by Django 5.0.6 on 2026-03-07 16:55

import subscriptions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='plan_features',
            field=models.JSONField(blank=True, default=subscriptions.models.default_plan_features),
        ),
    ]
