# Generated by Django 5.0.6 on 2026-02-28 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_seed_default_plans'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPaymentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rib', models.CharField(default='00799999004129827780', max_length=64)),
                ('instructions', models.TextField(default='Send money to this RIB and submit payment confirmation.')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription Payment Config',
                'verbose_name_plural': 'Subscription Payment Config',
            },
        ),
    ]
