# Generated by Django 5.0.6 on 2026-03-15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_remove_subscriptionpaymentproof_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpaymentrequest',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionpaymentrequest',
            name='status_reason_code',
            field=models.CharField(blank=True, choices=[('unreadable_proof', 'Unreadable proof'), ('amount_mismatch', 'Amount mismatch'), ('missing_reference', 'Missing transfer reference'), ('other', 'Other')], default='', max_length=40),
        ),
        migrations.AddField(
            model_name='subscriptionpaymentrequest',
            name='status_reason_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='subscriptionpaymentrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_subscription_payment_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
