# Generated by Django 5.0.6 on 2026-02-24 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InteractionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view', 'View Product'), ('click', 'Click Product'), ('search', 'Search Keyword'), ('filter_price', 'Filter by Price'), ('filter_dist', 'Filter by Distance'), ('filter_wilaya', 'Filter by Wilaya'), ('filter_rating', 'Filter by Rating'), ('contact', 'Contact Seller'), ('favorite', 'Add to Favorites'), ('negotiate', 'Request Negotiation'), ('share', 'Share Product'), ('compare', 'Compare Product')], max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('session_id', models.CharField(blank=True, default='', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Interaction Log',
                'verbose_name_plural': 'Interaction Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserInterestProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_scores', models.JSONField(blank=True, default=dict)),
                ('price_affinity', models.JSONField(blank=True, default=dict)),
                ('distance_sensitivity', models.FloatField(default=1.0)),
                ('quality_sensitivity', models.FloatField(default=1.0)),
                ('preferred_max_distance_km', models.FloatField(default=50.0)),
                ('preferred_wilayas', models.JSONField(blank=True, default=list)),
                ('search_keywords', models.JSONField(blank=True, default=dict)),
                ('preferred_sellers', models.JSONField(blank=True, default=list)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Interest Profile',
                'verbose_name_plural': 'User Interest Profiles',
            },
        ),
    ]
