# Generated by Django 5.0.6 on 2026-02-24 01:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interactionlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userinterestprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interest_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='interactionlog',
            index=models.Index(fields=['user', 'action', 'timestamp'], name='analytics_i_user_id_83ba79_idx'),
        ),
        migrations.AddIndex(
            model_name='interactionlog',
            index=models.Index(fields=['user', 'category'], name='analytics_i_user_id_cfc3af_idx'),
        ),
        migrations.AddIndex(
            model_name='interactionlog',
            index=models.Index(fields=['timestamp'], name='analytics_i_timesta_fa959f_idx'),
        ),
    ]
