# Generated by Django 5.0.6 on 2026-03-22 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_alter_interactionlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactionlog',
            name='action',
            field=models.CharField(choices=[('view', 'View Product'), ('click', 'Click Product'), ('store_click', 'Click Store'), ('promotion_click', 'Click Promotion'), ('search', 'Search Keyword'), ('filter_price', 'Filter by Price'), ('filter_dist', 'Filter by Distance'), ('filter_wilaya', 'Filter by Wilaya'), ('filter_rating', 'Filter by Rating'), ('contact', 'Contact Seller'), ('favorite', 'Add to Favorites'), ('negotiate', 'Request Negotiation'), ('share', 'Share Product'), ('compare', 'Compare Product'), ('rate', 'Rate Product/Store'), ('follow_store', 'Follow Store')], max_length=20),
        ),
    ]
