# Generated by Django 5.0.6 on 2026-02-13

from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		('users', '0002_remove_user_first_name_remove_user_last_name_and_more'),
	]

	operations = [
		migrations.AddField(
			model_name='user',
			name='gender',
			field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='', max_length=10),
		),
		migrations.AddField(
			model_name='user',
			name='birthday',
			field=models.DateField(blank=True, null=True),
		),
	]
