# Generated by Django 5.0.6 on 2026-01-06 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_replace_names_with_single_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
