# Generated by Django 5.0.6 on 2026-03-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_coins_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_login_coins', models.PositiveIntegerField(default=10, help_text='Amount of coins granted to new users upon registration.')),
                ('daily_login_coins', models.PositiveIntegerField(default=3, help_text='The target balance for daily login. If a user has less than this, they get topped up to this amount.')),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='last_daily_coin_grant',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
