# Generated by Django 5.0.6 on 2026-03-04 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_storereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allow_nearby_visibility',
            field=models.BooleanField(default=True, help_text='Whether this store can appear in nearby distance-based search.'),
        ),
    ]
