# Generated by Django 5.0.6 on 2026-03-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_allow_nearby_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_phone_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='show_social_public',
            field=models.BooleanField(default=True),
        ),
    ]
