# Generated by Django 5.0.6 on 2026-03-23 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_systemsettings_user_last_daily_coin_grant'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_quick_submit_seconds', models.PositiveIntegerField(default=20)),
                ('review_quick_submit_seconds', models.PositiveIntegerField(default=25)),
                ('minimum_interactions_for_high_credibility', models.PositiveIntegerField(default=3)),
                ('reporter_reputation_default', models.PositiveSmallIntegerField(default=50)),
                ('reporter_reputation_low_quality_penalty', models.PositiveSmallIntegerField(default=8)),
                ('reporter_reputation_good_report_bonus', models.PositiveSmallIntegerField(default=3)),
                ('report_weight_interactions', models.PositiveSmallIntegerField(default=40)),
                ('report_weight_recency', models.PositiveSmallIntegerField(default=20)),
                ('report_weight_reputation', models.PositiveSmallIntegerField(default=20)),
                ('report_weight_account_age', models.PositiveSmallIntegerField(default=20)),
                ('review_weight_dwell', models.PositiveSmallIntegerField(default=35)),
                ('review_weight_interactions', models.PositiveSmallIntegerField(default=35)),
                ('review_weight_account_age', models.PositiveSmallIntegerField(default=15)),
                ('review_weight_history', models.PositiveSmallIntegerField(default=15)),
                ('verified_min_credible_positive_reviews', models.PositiveIntegerField(default=10)),
                ('verified_max_credible_negative_ratio_percent', models.PositiveSmallIntegerField(default=20)),
                ('verified_min_account_age_days', models.PositiveIntegerField(default=30)),
                ('auto_verify_eligible_stores', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Trust Settings',
                'verbose_name_plural': 'Trust Settings',
            },
        ),
        migrations.AddField(
            model_name='storereport',
            name='evidence_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='storereport',
            name='is_low_credibility',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='storereport',
            name='reporter_reputation_score_at_submission',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storereport',
            name='scored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storereport',
            name='seriousness_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10),
        ),
        migrations.AddField(
            model_name='storereport',
            name='seriousness_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_status',
            field=models.CharField(choices=[('none', 'None'), ('eligible', 'Eligible'), ('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_stores', to=settings.AUTH_USER_MODEL),
        ),
    ]
