# Generated by Django 5.0.6 on 2026-02-21 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_facebook_user_instagram_user_tiktok_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location_updated_at',
            field=models.DateTimeField(blank=True, help_text='Last time GPS coordinates were changed', null=True),
        ),
    ]
