# Generated by Django 5.0.6 on 2026-03-23 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('problem', 'Problem'), ('suggestion', 'Suggestion')], max_length=20)),
                ('message', models.TextField()),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='feedback/screenshots/')),
                ('app_version', models.CharField(blank=True, default='', max_length=60)),
                ('platform', models.CharField(blank=True, default='', max_length=40)),
                ('device_info', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_review', 'In Review'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='open', max_length=20)),
                ('admin_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
