DEFAULT_SUBSCRIPTION_RIB = '00799999004129827780'
DEFAULT_SUBSCRIPTION_INSTRUCTIONS = (
	'Send money to this RIB and submit payment confirmation.'
)

DEFAULT_PLAN_FEATURES = {
	'promotion_enabled': True,
	'promotion_max_active': 1,
	'promotion_max_duration_days': 10,
	'promotion_max_impressions': 800,
	'recommendation_priority_boost': 0,
	'ad_enabled': True,
	'ad_max_active': 1,
	'ad_max_duration_days': 7,
	'ad_max_impressions': 600,
	'ad_priority_boost': 5,
}

DEFAULT_SUBSCRIPTION_PLANS = [
	{
		'name': 'Souk Starter',
		'slug': 'souk-starter',
		'max_products': 40,
		'price': '1200.00',
		'duration_days': 30,
		'benefits': 'Perfect for new stores starting out.\nBasic promotion tools and steady visibility.',
		'is_active': True,
		'plan_features': {
			'promotion_enabled': True,
			'promotion_max_active': 1,
			'promotion_max_duration_days': 7,
			'promotion_max_impressions': 1200,
			'recommendation_priority_boost': 4,
			'ad_enabled': True,
			'ad_max_active': 1,
			'ad_max_duration_days': 5,
			'ad_max_impressions': 900,
			'ad_priority_boost': 6,
			'ui_badge': 'New',
			'ui_gradient': ['#F6F8FF', '#E7ECFF'],
			'old_price': 1800,
		},
	},
	{
		'name': 'Bazaar Plus',
		'slug': 'bazaar-plus',
		'max_products': 140,
		'price': '3200.00',
		'duration_days': 30,
		'benefits': 'Faster growth with stronger reach.\nGreat for active stores.',
		'is_active': True,
		'plan_features': {
			'promotion_enabled': True,
			'promotion_max_active': 3,
			'promotion_max_duration_days': 14,
			'promotion_max_impressions': 9000,
			'recommendation_priority_boost': 10,
			'ad_enabled': True,
			'ad_max_active': 4,
			'ad_max_duration_days': 14,
			'ad_max_impressions': 6500,
			'ad_priority_boost': 12,
			'ui_badge': 'Popular',
			'ui_gradient': ['#FFF7E9', '#FFE4BF'],
			'old_price': 4500,
		},
	},
	{
		'name': 'Atlas Pro',
		'slug': 'atlas-pro',
		'max_products': 360,
		'price': '6900.00',
		'duration_days': 30,
		'benefits': 'Premium exposure + advanced ads.\nBuilt for top-performing stores.',
		'is_active': True,
		'plan_features': {
			'promotion_enabled': True,
			'promotion_max_active': 10,
			'promotion_max_duration_days': 30,
			'promotion_max_impressions': 55000,
			'recommendation_priority_boost': 20,
			'ad_enabled': True,
			'ad_max_active': 10,
			'ad_max_duration_days': 30,
			'ad_max_impressions': 42000,
			'ad_priority_boost': 22,
			'ui_badge': 'Best Value',
			'ui_gradient': ['#EEFDF5', '#D8F7E7'],
			'old_price': 9000,
		},
	},
]
