"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_dotenv_file() -> None:
    """Load simple KEY=VALUE pairs from app-backend/.env if present."""
    env_file = BASE_DIR / '.env'
    if not env_file.exists():
        return
    for raw_line in env_file.read_text(encoding='utf-8').splitlines():
        line = raw_line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, value = line.split('=', 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if key:
            os.environ.setdefault(key, value)


_load_dotenv_file()


def _env_bool(key: str, default: bool = False) -> bool:
    raw = os.environ.get(key)
    if raw is None:
        return default
    return str(raw).strip().lower() in {'1', 'true', 'yes', 'on'}


def _env_list(key: str, default: str = '') -> list[str]:
    raw = os.environ.get(key, default)
    return [item.strip() for item in str(raw).split(',') if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'dev-insecure-key-change-me')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool('DJANGO_DEBUG', default=True)

ALLOWED_HOSTS = _env_list('DJANGO_ALLOWED_HOSTS', default='*' if DEBUG else 'localhost,127.0.0.1')


# Application definition

INSTALLED_APPS = [
    # Admin theme (must precede django.contrib.admin)
    'jazzmin',

    # Django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'django_filters',
    'fcm_django',

    # Local
    'users',
    'catalog',
    'ads',
    'notifications',
    'subscriptions',
    'wallet',
    'analytics',
    'feedback',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'common.middleware.RequestIdMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# CORS Settings
CORS_ALLOW_ALL_ORIGINS = _env_bool('DJANGO_CORS_ALLOW_ALL_ORIGINS', default=DEBUG)
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = _env_list('DJANGO_CORS_ALLOWED_ORIGINS')

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'
ASGI_APPLICATION = 'backend.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if os.environ.get('POSTGRES_NAME'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('POSTGRES_NAME'),
            'USER': os.environ.get('POSTGRES_USER', 'postgres'),
            'PASSWORD': os.environ.get('POSTGRES_PASSWORD', ''),
            'HOST': os.environ.get('POSTGRES_HOST', 'db'),
            'PORT': os.environ.get('POSTGRES_PORT', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.OrderingFilter',
        'rest_framework.filters.SearchFilter',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.ScopedRateThrottle',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'anon': '60/min',
        'user': '300/min',
        'otp_send': '5/hour',
        'otp_verify': '20/hour',
        'report_create': '15/hour',
        'review_create': '30/hour',
        'payment_request_create': '20/hour',
        'ad_click': '180/hour',
        'analytics_events': '120/min',
        'trust_signals': '180/hour',
        'feedback_create': '20/hour',
    },
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}

AUTH_USER_MODEL = 'users.User'

FCM_DJANGO_SETTINGS = {
    'FCM_SERVER_KEY': os.environ.get('FCM_SERVER_KEY', ''),
    'ONE_DEVICE_PER_USER': False,
    'DELETE_INACTIVE_DEVICES': False,
}

JAZZMIN_SETTINGS = {
    'site_title': 'Backend Admin',
    'site_header': 'Backend Admin',
    'welcome_sign': 'Welcome',
    'copyright': 'Backend',
    'show_ui_builder': False,
    'icons': {
        'users.User': 'fas fa-user',
        'catalog.Product': 'fas fa-box',
        'catalog.Promotion': 'fas fa-bullhorn',
        'ads.AdCampaign': 'fas fa-bullseye',
        'notifications.Notification': 'fas fa-bell',
        'subscriptions.SubscriptionPlan': 'fas fa-tags',
    },
    'order_with_respect_to': [
        'users',
        'catalog',
        'ads',
        'notifications',
        'subscriptions',
    ],
}

# Recommendation system: controlled exploration (0.0 .. 0.30 recommended).
RECOMMENDATION_EXPLORATION_RATE = float(os.environ.get('RECOMMENDATION_EXPLORATION_RATE', '0.10'))

# Celery Settings
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# Run Celery tasks eagerly strictly in development environment (without a worker)
CELERY_TASK_ALWAYS_EAGER = DEBUG

# Twilio WhatsApp OTP
TWILIO_ACCOUNT_SID = os.environ.get('TWILIO_ACCOUNT_SID', '')
TWILIO_AUTH_TOKEN = os.environ.get('TWILIO_AUTH_TOKEN', '')
TWILIO_FROM_NUMBER = os.environ.get('TWILIO_FROM_NUMBER', '')
TWILIO_WHATSAPP_FROM = os.environ.get('TWILIO_WHATSAPP_FROM', 'whatsapp:+14155238886')
TWILIO_WHATSAPP_CONTENT_SID = os.environ.get('TWILIO_WHATSAPP_CONTENT_SID', '')
TWILIO_OTP_CHANNEL = os.environ.get('TWILIO_OTP_CHANNEL', 'whatsapp')  # whatsapp | sms | both

# Coin economy settings
INITIAL_SIGNUP_COINS = int(os.environ.get('INITIAL_SIGNUP_COINS', '40'))
COST_PRODUCT_POST_COINS = int(os.environ.get('COST_PRODUCT_POST_COINS', '4'))
COST_PACK_POST_COINS = int(os.environ.get('COST_PACK_POST_COINS', '2'))
COST_PROMOTION_POST_COINS = int(os.environ.get('COST_PROMOTION_POST_COINS', '2'))
COST_AD_VIEW_COIN = int(os.environ.get('COST_AD_VIEW_COIN', '1'))

COIN_PACKS = [
    {'id': 'pack_50', 'coins': 50, 'price': '500'},
    {'id': 'pack_120', 'coins': 120, 'price': '1000'},
    {'id': 'pack_200', 'coins': 200, 'price': '1500'},
    {'id': 'pack_500', 'coins': 500, 'price': '3500'},
]

# Initialize Firebase Admin SDK
import firebase_admin
from firebase_admin import credentials

cred_path = os.environ.get('GOOGLE_APPLICATION_CREDENTIALS', str(BASE_DIR / 'firebase-adminsdk.json'))
if os.path.exists(cred_path):
    cred = credentials.Certificate(cred_path)
    if not firebase_admin._apps:
        firebase_admin.initialize_app(cred)
else:
    print(f"Warning: Firebase credentials not found at {cred_path}. Push notifications will not work.")

# Add HEIC support for uploaded images
try:
    from pillow_heif import register_heif_opener
    register_heif_opener()
except ImportError:
    print("pillow-heif not installed, HEIC image uploads might fail.")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
