# Generated by Django 5.0.6 on 2026-03-22 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_remove_coin_type_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coinpackplan',
            options={'ordering': ['sort_order', 'coins_amount', 'id']},
        ),
    ]
