const Map<String, List<String>> algeriaWilayasBaladiat = {
  // --- 1 to 48 (Classic Wilayas - Adjusted for 2021 splits) ---
  'Adrar': [
    'Adrar', 'Reggane', 'Aoulef', 'Zaouiet Kounta', 'Tsabit', 'Fenoughil', 'In Zghmir', 
    'Ouled Ahmed Timmi', 'Tamest', 'Tit', 'Bouda', 'Sali', 'Akabli', 'Sebaa', 
    'Ouled Aissa', 'Talmine' 
    // Timimoun & BBM moved to Wilayas 49 & 50
  ],
  'Chlef': [
    'Chlef', 'Tenes', 'Oued Fodda', 'El Karimia', 'Boukadir', 'Oum Drou', 
    'Sendjas', 'Beni Haoua', 'El Marsa', 'Abou El Hassan', 'Beni Bouateb', 
    'Chettia', 'Sidi Akkacha', 'Oued Sly', 'Sidi Abderrahmane', 'Tadjena', 
    'Talassa', 'Zeboudja', 'El Hadjadj', 'Labiod Medjadja', 'Breira', 
    'Ouled Ben Abdelkader', 'Taougrite', 'Beni Rached', 'Herenfa', 'Ain Merane', 
    'Sobha', 'Mansourah', 'Oued Goussine'
  ],
  'Laghouat': [
    'Laghouat', 'Ksar El Hirane', 'Benoud', 'El Houaita', 'Hassi Delaa', 
    'Hassi R\'Mel', 'Ain Madhi', 'Tadjemout', 'Kheneg', 'Gueltat Sidi Saad', 
    'Ain Sidi Ali', 'Beidha', 'Brida', 'El Ghicha', 'Hadj Mechri', 'Sebgag', 
    'Taouiala', 'Tadjrouna', 'Aflou', 'El Assafia', 'Oued Morra', 'Oued M\'Zi', 
    'Sidi Bouzid', 'Sidi Makhlouf'
  ],
  'Oum El Bouaghi': ['Oum El Bouaghi', 'Ain Beida', 'Ain M\'lila', 'Ain Fakroun', 'Ain Babouche', 'Berriche', 'Ouled Hamla', 'Dhalaa', 'El Amiria', 'Sigus', 'Oued Nini', 'Fkirina', 'Souk Naamane', 'Zorg', 'El Fedjoudj Boughrara Saoudi', 'Ouled Zouai', 'Bir Chouhada', 'Ksar Sbahi', 'Ouled Gacem', 'El Harmilia', 'Hanchir Toumghani', 'Rahia', 'Meskiana', 'Ain Diss', 'Bougherara', 'Ouled Djellal'], // Partial list
  'Batna': ['Batna', 'Barika', 'Merouana', 'Ain Touta', 'El Madher', 'Tazoult', 'N\'Gaous', 'Arris', 'Ain Djasser', 'Seriana', 'Timgad', 'Ras El Aioun', 'Fesdis', 'Oued El Ma', 'Teniet El Abed', 'Inoughissen', 'Boumagueur', 'Djerma', 'Maafa', 'Ghassira', 'Kimmel'], // Partial list
  'Béjaïa': ['Béjaïa', 'Amizour', 'Feraoun', 'Taourirt Ighil', 'Chellata', 'Tamakra', 'Timezrit', 'Souk El Tenine', 'M\'cisna', 'Tinabdher', 'Tichy', 'Semaoun', 'Kendira', 'Tifra', 'Ighram', 'Amalou', 'Ighil Ali', 'Fenaia Ilmaten', 'Toudja', 'Darguina', 'Sidi-Ayad', 'Aokas', 'Beni Djellil', 'Beni Maouche', 'Oued Ghir', 'Boudjellil', 'Akbou'], // Partial list
  'Biskra': ['Biskra', 'Oumache', 'Branis', 'Chetma', 'Ouled Djellal', 'Ras El Miaad', 'Besbes', 'Sidi Khaled', 'Doucen', 'Chaiba', 'Sidi Okba', 'M\'Chouneche', 'El Haouch', 'Ain Naga', 'Zeribet El Oued', 'El Mizaraa', 'El Kantara', 'Ain Zaatout', 'Tolga', 'Bouchagroune', 'Lichana', 'Bordj Ben Azzouz', 'Lioua', 'M\'Lili', 'Foughala', 'El Ghrous', 'El Hadjib'], // Note: Ouled Djellal is now Wilaya 51, but strictly administratively some lists split them.
  'Béchar': ['Béchar', 'Erg Ferradj', 'Ouled Khoudir', 'Meridja', 'Timoudi', 'Lahmar', 'Beni Abbes', 'Beni Ikhlef', 'Mechraa Houari Boumedienne', 'Kenadsa', 'Igli', 'Tabalbala', 'Taghit', 'El Ouata', 'Boukais', 'Mogheul', 'Abadla', 'Kerzaz', 'Ksabi', 'Tamtert', 'Beni Ounif'],
  'Blida': ['Blida', 'Chebli', 'Bouinan', 'Oued El Alleug', 'Ouled Yaich', 'Chrea', 'El Affroun', 'Chiffa', 'Hammam Melouane', 'Benkhelil', 'Soumaa', 'Mouzaia', 'Souk El Had', 'Ouled Slama', 'Boufarik', 'Meftah', 'Chiffa', 'Ain Romana', 'Bouarfa', 'Beni Mered', 'Bougara', 'Guerrouaou', 'Beni Tamou', 'Djebabra', 'Larbaa'],
  'Bouira': ['Bouira', 'El Asnam', 'Guerrouma', 'Souk El Khemis', 'Kadiria', 'Hanif', 'Dirah', 'Ait Laaziz', 'Taghzout', 'Raouraoua', 'Mezdour', 'Haizer', 'Lakhdaria', 'Maala', 'El Hachimia', 'Aomar', 'Chorfa', 'Bordj Okhriss', 'El Adjiba', 'El Hakimia', 'El Khebouzia', 'Ahl El Ksar', 'Bouderbala', 'Zbarbar', 'Ain El Hadjar', 'Djebahia', 'Sour El Ghozlane', 'Bechloul', 'Sidi Aissa', 'Ain Turki', 'Boukram', 'Ain Bessam', 'Bir Ghbalou', 'M\'Chedallah', 'Souk El Khemis', 'Ridane', 'Ain Laloui', 'Oued El Berdi', 'El Mokrani', 'Dechmia', 'Ridanes', 'El Esnam'],
  'Tamanrasset': ['Tamanrasset', 'Abalessa', 'In Ghar', 'In Guezzam', 'Idles', 'Tazrouk', 'Tin Zaouatine', 'In Salah', 'In Amguel', 'Foggaret Ezzaouia'], // In Salah & In Guezzam are now Wilayas 53 & 54
  'Tébessa': ['Tébessa', 'Bir El Ater', 'Cheria', 'Stah Guentis', 'El Aouinet', 'El Hamma El Khroub', 'Hammamet', 'Bir Mokkadem', 'Morsott', 'Ogla', 'Boulhaf Dir', 'Bedjene', 'El Mezeraa', 'Ouenza', 'El Ma Labiodh', 'Ain Zerga', 'Boukhadra', 'Houidjbet', 'El Kouif', 'Ferkane', 'Negrine', 'El Ogla', 'Bir Dheb', 'Tiliouine', 'Safsaf El Ouesra', 'Oum Ali', 'Thlidjene', 'Ain Farrat'],
  'Tlemcen': ['Tlemcen', 'Mansourah', 'Chetouane', 'Amieur', 'Ain Fezza', 'Hennaya', 'Zenata', 'Ouled Mimoun', 'Oued Chouly', 'Beni Semiel', 'Ain Youcef', 'Remchi', 'El Fehoul', 'Sebdou', 'Beni Ouarsous', 'Sidi Medjahed', 'Beni Boussaid', 'Sidi Djillali', 'Beni Bahdel', 'El Gor', 'El Aricha', 'Bouihi', 'Maghnia', 'Hammam Boughrara', 'Seniesselt', 'Ain Tallout', 'Ain Nehala', 'Ouled Riyah', 'Honaine', 'Beni Khellad', 'Sidi Abdelli', 'Souk Tleta', 'Bab El Assa', 'Souani', 'Fellaoucene', 'Ghazaouet', 'Souahlia', 'Tianet', 'Dar Yaghmouracene', 'Nedroma', 'Djebala', 'Ain Kebira', 'Beni Mester', 'Ain Ghoraba', 'Terny Beni Hdiel', 'Bensekrane', 'Sidi El Abdelli', 'Sidi Boumedienne', 'Beni Snous', 'Azails', 'Sebbaa Chioukh', 'Marsa Ben M\'Hidi', 'Msirda Fouaga'],
  'Tiaret': ['Tiaret', 'Medroussa', 'Ain Bouchekif', 'Sidi Ali Mellal', 'Ain Zarit', 'Ain Deheb', 'Naima', 'Mechraa Safa', 'Frenda', 'Takhemaret', 'Tousnina', 'Dahmouni', 'Rahouia', 'Mahdia', 'Sougueur', 'Sidi Abdelghani', 'Ain El Hadid', 'Ouled Yerou', 'Nadorah', 'Tidda', 'Oued Lilli', 'Sidi Bakhti', 'Serghine', 'Zmalet El Emir Abdelkader', 'Madna', 'Sebt', 'Mellakou', 'Ksar Chellala', 'Guertoufa', 'Sidi Hosni', 'Djillali Ben Amar', 'Sebaine', 'Chhaima', 'Ain Kermes', 'Bougara', 'Chellala', 'Rechaiga', 'Hamadia', 'Rosfa', 'Oued Lilli', 'Faidja', 'Si Abdelghani'],
  'Tizi Ouzou': ['Tizi Ouzou', 'Ain El Hammam', 'Akbil', 'Freha', 'Souamaa', 'Mechtras', 'Irdjen', 'Timizart', 'Makouda', 'Draâ El Mizan', 'Tizi Gheniff', 'Boghni', 'Ifigha', 'Azazga', 'Larbaâ Nath Irathen', 'Ait Yenni', 'Ouadhias', 'Azeffoun', 'Tigzirt', 'Djebel Aissa Mimoun', 'Beni Douala', 'Ouaguenoun', 'Maatkas', 'Beni Zmenzer', 'Sidi Namane', 'Tadmait', 'Draa Ben Khedda', 'Tirmitine', 'Ait Mahmoud', 'Beni Aissi', 'Ait Bouaddou', 'Assi Youcef', 'Bounouh', 'Frikat', 'Ain Zaouia', 'M\'Kira', 'Ait Yahia', 'Ait Khellili', 'Souk El Tenine', 'Ait Chafaa', 'Zekri', 'Akerrou', 'Yatafen', 'Iferhounene', 'Illilten', 'Abi Youcef', 'Beni Yenni', 'Iboudraren', 'Tizi Rached', 'Ait Oumalou', 'Tizi N\'Tleta', 'Ait Toudert', 'Mechtras', 'Ouacif', 'Ait Boumahdi', 'Agouni Gueghrane', 'Beni Ziki', 'Bouzeguene', 'Idjeur', 'Illoula Oumalou', 'Yakouren', 'Mizrana', 'Ait Aissa Mimoun', 'Iflissen', 'Boudjima'],
  'Algiers': ['Alger Centre', 'Sidi M\'Hamed', 'El Madania', 'Belouizdad', 'Bab El Oued', 'Bologhine', 'Casbah', 'Oued Koriche', 'Bir Mourad Rais', 'El Biar', 'Bouzareah', 'Birkhadem', 'El Harrach', 'Baraki', 'Oued Smar', 'Bachedjerah', 'Hussein Dey', 'Kouba', 'Bourouba', 'Dar El Beida', 'Bab Ezzouar', 'Ben Aknoun', 'Dely Ibrahim', 'El Hammamet', 'Rais Hamidou', 'Djasr Kasentina', 'El Mouradia', 'Hydra', 'Mohammadia', 'Bordj El Kiffan', 'El Magharia', 'Beni Messous', 'Les Eucalyptus', 'Birtouta', 'Tessala El Merdja', 'Ouled Chebel', 'Sidi Moussa', 'Ain Taya', 'Bordj El Bahri', 'El Marsa', 'Haraoua', 'Rouiba', 'Reghaia', 'Ain Benian', 'Staoueli', 'Zeralda', 'Mahelma', 'Rahmania', 'Souidania', 'Cheraga', 'Ouled Fayet', 'El Achour', 'Draria', 'Douera', 'Baba Hassen', 'Khraicia', 'Saoula'],
  'Djelfa': ['Djelfa', 'Moudjebara', 'El Guedid', 'Hassi Bahbah', 'Ain Oussara', 'Messaad', 'Birine', 'Dar Chioukh', 'Charef', 'El Idrissia', 'Ain El Ibel', 'Sidi Ladjel', 'Had Sahary', 'Guernini', 'Bouira Lahdab', 'Ain Feka', 'Zaafrane', 'Hassi El Euch', 'Ain Chouhada', 'Douis', 'Benhar', 'Faidh El Botma', 'Amourah', 'Oum Laadham', 'Mliliha', 'Sidi Baizid', 'Beni Yagoub', 'Deldoul', 'Selmana', 'Sed Rahal', 'Guettara', 'El Khemis', 'Hassi Fedoul', 'Ain Maabed', 'Zaccar', 'El Ogued'],
  'Jijel': ['Jijel', 'El Aouana', 'Selma Benziada', 'Erraguene', 'Bouchtata', 'Texenna', 'Djhimla', 'Kaous', 'Emir Abdelkader', 'Ouled Yahia Khadrouche', 'Boraheddine', 'Sidi Marouf', 'Chekfa', 'El Kennar', 'Bordj Tahar', 'El Milia', 'Ouled Rabah', 'Sidi Abdelaziz', 'Settara', 'Ghebala', 'Bouraoui Belhadef', 'El Ancer', 'Khiri Oued Adjoul', 'Djimla', 'Oudjana', 'Taher', 'Chahna', 'Ouled Askeur', 'Ziama Mansouriah'],
  'Sétif': ['Sétif', 'Ain El Kebira', 'Beni Aziz', 'Ouled Sidi Ahmed', 'Ain Oulmene', 'Beidha Bordj', 'Bouandas', 'Bousselam', 'Hamam Guergour', 'Ait Naoual Mezada', 'Ait Tizi', 'Bougaa', 'Ain Roua', 'Beni Ouartilane', 'El Ouricia', 'Guenzet', 'Ain Azel', 'Ain Lahdjar', 'Bir El Arch', 'Belaa', 'Tachouda', 'Tala Ifacene', 'Serdj El Ghoul', 'Guidjel', 'Ouled Sabor', 'Bazer Sakhra', 'El Eulma', 'Guelta Zerka', 'Beni Fouda', 'Djemila', 'Ain Legraj', 'Beni Chebana', 'Dehamcha', 'Beni Ourtilane', 'Ain Sebt', 'Hammam Soukhna', 'Taya', 'Ain Abessa', 'Salah Bey', 'Ain Arnat', 'Mezloug', 'Bir Haddada', 'Rasfa', 'Ouled Tebben', 'Hamma', 'Maaouia', 'Ain Zalat', 'Tizi N\'Bechar', 'Amoucha', 'Oued El Barad', 'Tella', 'Boutaleb', 'Ouled Addouane', 'Beni Mouhli', 'Ouled Si Ahmed', 'Ait Tizi', 'Maoklane', 'Guellal', 'Ksar El Abtal', 'Ouled Adouane'],
  'Saïda': ['Saïda', 'Doui Thabet', 'Ain El Hadjar', 'Ouled Khaled', 'Moulay Larbi', 'Youb', 'Hounet', 'Sidi Amar', 'Sidi Boubekeur', 'El Hassasna', 'Maamora', 'Ain Sekhouna', 'Ouled Brahim', 'Tircine', 'Ain Soltane', 'Ouled Bekkai'],
  'Skikda': ['Skikda', 'Ain Zouit', 'El Hadaiek', 'Azzaba', 'Djendel Saadi Mohamed', 'Ain Charchar', 'Es Sebt', 'Bekkouche Lakhdar', 'Ben Azzouz', 'El Marsa', 'El Harrouch', 'Zerdazas', 'Ouled Hebaba', 'Emjez Edchich', 'Salah Bouchaour', 'Collo', 'Beni Zid', 'Cheraia', 'Tamalous', 'Kerkera', 'Bin El Ouiden', 'Azzaba', 'Bouchetata', 'Filfila', 'Hammadi Krouma', 'Kanoua', 'Kheneg Mayoum', 'Oum Toub', 'Ramdane Djamel', 'Sidi Mezghiche'],
  'Sidi Bel Abbès': ['Sidi Bel Abbès', 'Tessala', 'Sidi Brahim', 'Mostefa Ben Brahim', 'Telagh', 'Mezaourou', 'Boukhanafis', 'Sidi Ali Boussidi', 'Sidi Lahcene', 'Amarnas', 'Tilmouni', 'Sidi Khaled', 'Ain El Berd', 'Sfisef', 'M\'Cid', 'Boudjebaa El Bordj', 'Ain Tindamine', 'Zerouala', 'Lamtar', 'Sidi Hamadouche', 'Sidi Chaib', 'Makedra', 'Ain Adden', 'Ain Thrid', 'Sehala Thaoura', 'Teghalimet', 'Hassi Dahou', 'Oued Sefioun', 'Tenira', 'Moulay Slissen', 'El Hacaiba', 'Hassi Zehana', 'Ben Badis', 'Sidi Yacoub', 'Sidi Daho', 'Belarbi', 'Oued Sebaa', 'Marhoum', 'Bir El Hammam', 'Merine', 'Tafissour', 'Ras El Ma', 'Oued Taourira', 'Redjem Demouche', 'Dhaya', 'Tenira', 'Ain Kada', 'Sidi Ali Benyoub', 'Boukhanefis', 'Tabia', 'Chettouane Belaila'],
  'Annaba': ['Annaba', 'Berrahal', 'El Hadjar', 'Eulma', 'El Bouni', 'Oued El Aneb', 'Cheurfa', 'Seraidi', 'Ain Berda', 'Chetaibi', 'Sidi Amar', 'Treat'],
  'Guelma': ['Guelma', 'Nechmaya', 'Bouati Mahmoud', 'Oued Zenati', 'Tamlouka', 'Ain Sandel', 'Ras El Agba', 'Oued Cheham', 'Dahouara', 'Ain Makhlouf', 'Ain Ben Beida', 'Bouchegouf', 'Medjez Sfa', 'Oued Fragha', 'Ain Larbi', 'Belkheir', 'Beni Mezline', 'Guelaat Bou Sbaa', 'Heleiokopolis', 'El Fedjoudj', 'Hammam Debagh', 'Roknia', 'Bouhamdane', 'Bordj Sabath', 'Hamman N\'Bail', 'Ain Hessania', 'Djeballah Khemissi', 'Bou Hachana', 'Khezarra', 'Sellaoua Announa', 'Medjez Amar', 'Ain Reggada', 'Houari Boumedienne', 'Roknia', 'Ras El Agba'],
  'Constantine': ['Constantine', 'El Khroub', 'Ain Smara', 'Hamma Bouziane', 'Didouche Mourad', 'Zighoud Youcef', 'Beni Hamidane', 'Ouled Rahmoune', 'Ain Abid', 'Ben Badis', 'Ibn Ziad', 'Messaoud Boudjeriou'],
  'Médéa': ['Médéa', 'Ouzera', 'Ouled Maaref', 'Ain Boucif', 'Aissaouia', 'Ouled Deide', 'El Omaria', 'Derrag', 'Tletat Ed Douair', 'Beni Slimane', 'Berrouaghia', 'Seghouane', 'Mezerana', 'Tablat', 'Deux Bassins', 'Sid Naamane', 'El Azizia', 'Ksar El Boukhari', 'El Ouinet', 'Saneg', 'M\'fatha', 'Ouled Antar', 'Boughezoul', 'Chahbounia', 'Si Mahdjoub', 'Ouled Bouachra', 'Oum El Djalil', 'Djouab', 'Sidi Ziane', 'Sidi Demed', 'Baata', 'El Hamdania', 'Ouled Brahim', 'Bir Ben Laabed', 'El Guelb El Kebir', 'Sedraia', 'Ain Ouksir', 'Tamesguida', 'Rebaia', 'Boughzoul', 'Ouled Hellal', 'Hannacha', 'Ouled Turqui', 'Bouchrahil', 'Sidi Rabie', 'Mihoub', 'Aziz', 'Chellalat El Adhaoura', 'Cheniguel', 'Tafraout', 'Ain Ouksir', 'Souagui', 'Zoubiria', 'Maghraoua', 'Kef Lakhdar'],
  'Mostaganem': ['Mostaganem', 'Sayada', 'Fornaka', 'Stidia', 'Ain Nouissy', 'Hassi Mameche', 'Mazagran', 'Ain Tedles', 'Sidi Belattar', 'Sour', 'Oued El Kheir', 'Sidi Ali', 'Ouled Maallah', 'Tazgait', 'Safsaf', 'Mansourah', 'Mesra', 'Ain Sidi Cherif', 'Blad Touahria', 'Sirat', 'Bouguirat', 'Souaflia', 'Sidi Lakhdar', 'Hadjadj', 'Benabdelmalek Ramdane', 'Nekmaria', 'Achacha', 'Khadra', 'Ouled Boughalem', 'Achaacha', 'Kheir Eddine', 'Ain Boudinar'],
  'M\'Sila': ['M\'Sila', 'Hammam Dalaa', 'Ouled Derradj', 'Tarmount', 'M\'Tarfa', 'Maadid', 'Ouled Addi Guebala', 'Ouled Mansour', 'Sidi Aissa', 'Bouti Sayah', 'Beni Ilmane', 'Sidi Hadjeres', 'Ain El Hadjel', 'Bou Saada', 'El Hamel', 'Oultene', 'Djebel Messaad', 'Ouled Slimane', 'Ben Srour', 'Ouled Mohamed', 'Zarzour', 'Mohamed Boudiaf', 'Ouled Sidi Brahim', 'Ain Khadra', 'Belaiba', 'Berhoum', 'Dehahna', 'Magra', 'Ain El Melh', 'Bir Foda', 'Ain Fares', 'Sidi M\'Hamed', 'Ain Errich', 'El Houamed', 'Slim', 'Ouanougha', 'Sidi Ameur', 'Tamsa', 'Ben Zouh', 'Khoubana', 'M\'Cif', 'Chellal', 'Ouled Madhi', 'Khettouti Sed El Djir', 'Souamaa', 'Ouled Atia', 'Benzouh'],
  'Mascara': ['Mascara', 'Bou Hanifia', 'Tizi', 'Froha', 'Ghriss', 'Matemore', 'Oued El Abtal', 'Sidi Abdeldjebar', 'Sehailia', 'Sidi Kada', 'Oued Taria', 'Guerdjoum', 'Ain Fekan', 'Ain Ferah', 'Oued El Abtal', 'Sidi Boussaid', 'El Bordj', 'Khalouia', 'Menouer', 'Zelamta', 'Tighennif', 'Hachem', 'Sidi Abdelmoumen', 'Chorfa', 'El Keurt', 'Ain Fares', 'Mamounia', 'El Gaada', 'Zahana', 'Mocta Douz', 'Sig', 'Oggaz', 'Alaimia', 'Ras El Ain Amirouche', 'Bou Henni', 'El Guettana', 'Benian', 'Aouf', 'Gharrous', 'Nesmot', 'Matmore', 'Sidi Ali Benyoub', 'Maoussa', 'Mohammadia', 'Ferraguig', 'El Ghomri', 'Sedjerara', 'Sidiada'],
  'Ouargla': ['Ouargla', 'Ain Beida', 'N\'Goussa', 'Hassi Messaoud', 'Rouissat', 'Sidi Khouiled', 'Hassi Ben Abdellah', 'El Borma'], // Touggourt split to Wilaya 55
  'Oran': ['Oran', 'Es Senia', 'Bir El Djir', 'Sidi Chami', 'El Kerma', 'Misserghin', 'Boutlelis', 'Ain El Turk', 'Bousfer', 'El Ancon', 'Mers El Kebir', 'Arzew', 'Sidi Ben Yebka', 'Ain Bya', 'Bethioua', 'Marsat El Hadjadj', 'Ain El Kerma', 'Gdyel', 'Ben Freha', 'Hassi Mefsoukh', 'Hassi Ben Okba', 'Hassi Bounif', 'El Braya', 'Boufatis', 'Oued Tlelat', 'Tafraoui'],
  'El Bayadh': ['El Bayadh', 'Rogassa', 'Stitten', 'Brezina', 'Ghassoul', 'Boualem', 'Sidi Ameur', 'Sidi Tifour', 'Sidi Slimane', 'Kef El Ahmar', 'El Mehara', 'Tousmouline', 'Cheguig', 'El Bnoud', 'El Abiodh Sidi Cheikh', 'Ain El Orak', 'Arbaouat', 'Kraakda', 'Maamora', 'Bougtob', 'El Kheiter', 'Chellala'],
  'Illizi': ['Illizi', 'Debdeb', 'Bordj Omar Driss', 'In Amenas'], // Djanet split to Wilaya 56
  'Bordj Bou Arreridj': ['Bordj Bou Arreridj', 'Ras El Oued', 'Bordj Zemoura', 'Mansoura', 'El M\'hir', 'Ben Daoud', 'El Hamadia', 'El Achir', 'Rabta', 'Khelil', 'Sidi Embarek', 'Ain Taghrout', 'Tixter', 'Bir Kasdali', 'Tefreg', 'El Main', 'Djaafra', 'Colla', 'Teniet En Nasr', 'El Euch', 'Ksour', 'Ouled Brahem', 'Ain Tesra', 'Belimour', 'Ouled Dahmane', 'Ghilassa', 'Taglait', 'Bordj Ghdir', 'El Anseur', 'Haraza', 'Ouled Sidi Brahim', 'Ain Ksiba', 'Sidi Ahcene', 'Hasnaoua', 'Medjana'],
  'Boumerdès': ['Boumerdès', 'Boudouaou', 'Afir', 'Bordj Menaiel', 'Baghlia', 'Sidi Daoud', 'Naciria', 'Djinet', 'Isser', 'Zemmouri', 'Si Mustapha', 'Tidjelabine', 'Chabet El Ameur', 'Thenia', 'Beni Amrane', 'Khemis El Khechna', 'Ouled Moussa', 'Larbatache', 'Kharrouba', 'Hammedi', 'Corso', 'Dellys', 'Ben Choud', 'Ammal', 'Timezrit', 'Ouled Hedadj', 'Leghata', 'Ouled Aissa', 'Souk El Had', 'Boudouaou El Bahri', 'Bouzegza Keddara'],
  'El Tarf': ['El Tarf', 'Bouhadjar', 'Ben M\'Hidi', 'El Kala', 'Ain El Assel', 'El Aioun', 'Bouteldja', 'Souarekh', 'Berrihane', 'Lac Des Oiseaux', 'Chefia', 'Drean', 'Chihani', 'Chebaita Mokhtar', 'Besbes', 'Asfour', 'Zeriizer', 'Ain Kerma', 'Bougous', 'Raml Souk', 'El Chatt', 'Ain El Assel', 'Hammam Beni Salah', 'Oued Zitoun'],
  'Tindouf': ['Tindouf', 'Oum El Assel'],
  'Tissemsilt': ['Tissemsilt', 'Bordj Bounaama', 'Theniet El Had', 'Lazharia', 'Beni Chaib', 'Lardjem', 'Melaab', 'Sidi Abed', 'Sidi Boutouchent', 'Sidi Lantri', 'Tamalahat', 'Boucaid', 'Beni Lahcene', 'Ammari', 'Maacem', 'Sidi Slimane', 'Boukhemis', 'Khemisti', 'Ouled Bessem', 'Youssoufia', 'Layoune', 'Beni Chaib'],
  'El Oued': ['El Oued', 'Robbah', 'Oued El Alenda', 'Bayadha', 'Nakhla', 'Guemar', 'Kouinine', 'Reguiba', 'Hamraia', 'Taghzout', 'Debila', 'Hassani Abdelkrim', 'Hassi Khalifa', 'Taleb Larbi', 'Douar El Ma', 'Ben Guecha', 'Mih Ouansa', 'Oum Touyour', 'Sidi Aoun', 'El Ogla', 'Magrane', 'Trifa'], // El M'Ghair split to Wilaya 57
  'Khenchela': ['Khenchela', 'Mtoussa', 'Baghai', 'El Hamma', 'Ensigha', 'Tamza', 'Ain Touila', 'Ouled Rechache', 'Mahhmal', 'Djellal', 'Khirane', 'Bouhmama', 'Chechar', 'Babar', 'El Oueldja', 'Yabous', 'Kais', 'Remila', 'Taouzianat', 'M\'Sara', 'Chilia'],
  'Souk Ahras': ['Souk Ahras', 'Sedrata', 'Hanancha', 'Machroha', 'Ouled Driss', 'Tiffech', 'Zaarouria', 'Taoura', 'Drea', 'Haddada', 'Khedara', 'Merahna', 'Ouled Moumen', 'Bir Bouhouch', 'M\'Daourouch', 'Oum El Adhaim', 'Ragouba', 'Sidi Fredj', 'Ain Zana', 'Ain Soltane', 'Khemissa', 'Ouled Bechih', 'Terragvelt', 'Zouabi', 'Safel El Ouiden', 'Hammam N\'Bail'],
  'Tipaza': ['Tipaza', 'Menaceur', 'Larhat', 'Douaouda', 'Bourkika', 'Khemisti', 'Aghbal', 'Hadjout', 'Sidi Amar', 'Gouraya', 'Nador', 'Chaiba', 'Ain Tagourait', 'Cherchell', 'Damous', 'Merad', 'Fouka', 'Bou Ismail', 'Ahmar El Ain', 'Bouharoun', 'Sidi Ghiles', 'Messelmoun', 'Sidi Rached', 'Kolea', 'Attatba', 'Sidi Semiane', 'Beni Milleuk', 'Hadjeret Ennous'],
  'Mila': ['Mila', 'Ferdjioua', 'Chelghoum Laid', 'Oued Endja', 'Rouached', 'Tiberguent', 'Ahmed Rachedi', 'Zeghaia', 'Oued Seguen', 'Teleghma', 'Amira Arres', 'Terrai Bainen', 'Tassadane Haddada', 'Minar Zarza', 'Sidi Merouane', 'Chigara', 'Hamala', 'Grarem Gouga', 'Tessala Lemtai', 'Bouhatem', 'Derrahi Bousselah', 'Ain Beida Harriche', 'El Ayadi Barbes', 'Ain Tine', 'El Mechira', 'Oued Athmenia', 'Ain Mellouk', 'Benyahia Abderrahmane', 'Ouled Khalouf', 'Tadjenanet', 'Yahia Beniguecha', 'Ain Beida Harriche'],
  'Aïn Defla': ['Aïn Defla', 'Miliana', 'Boumedfaa', 'Khemis Miliana', 'Hammam Righa', 'Arib', 'Djelida', 'Al Amra', 'Bourached', 'El Attaf', 'Tiberkanine', 'Ain Bouyahia', 'El Abadia', 'Tacheta Zougagha', 'Zeddine', 'El Maine', 'Rouina', 'Ain Lechiekh', 'Djendel', 'Oued Chorfa', 'Bir Ould Khelifa', 'Bordj Emir Khaled', 'Tarik Ibn Ziad', 'Bathia', 'Belaas', 'Hassania', 'Ben Allal', 'Sidi Lakhdar', 'Ain Torki', 'Ain Soltane', 'Oued Djemaa', 'El Amra', 'Mekhatria', 'Ain Benian', 'Barbouche', 'Djemaa Ouled Cheikh'],
  'Naâma': ['Naâma', 'Mecheria', 'Ain Sefra', 'Tiout', 'Sfissifa', 'Moghrar', 'Assela', 'Djeniene Bourezg', 'Ain Ben Khelil', 'Makman Ben Amer', 'Kasdir', 'El Biodh'],
  'Aïn Témouchent': ['Aïn Témouchent', 'Hammam Bouhadjar', 'Beni Saf', 'El Amria', 'El Malah', 'Ain El Arbaa', 'Tamzoura', 'Chat El Hilal', 'Sidi Ben Adda', 'Aoubellil', 'Ain Kihal', 'Aghlal', 'Terga', 'Oulhaça El Gheraba', 'Sidi Ouriache', 'Emir Abdelkader', 'Hassi El Ghella', 'Ouled Kihal', 'Chaabat El Leham', 'Ain Tolba', 'Sidi Boumedienne', 'Oued Sebbah', 'Sidi Safi', 'Oued Berkeche', 'Hassasna', 'Bouzedjar', 'El Messaid', 'Ouled Boudjemaa'],
  'Ghardaïa': ['Ghardaïa', 'Metlili', 'El Guerara', 'El Atteuf', 'Dhayet Ben Dhahoua', 'Berriane', 'Sebseb', 'Zelfana', 'Bounoura'], // El Meniaa split to Wilaya 58
  'Relizane': ['Relizane', 'Oued Rhiou', 'Gelaat Bousbaa', 'Sidi Khettab', 'Belassel Bouzegza', 'El Matmar', 'Sidi M\'Hamed Benaouda', 'Bendaoud', 'Zemmoura', 'Beni Dergoun', 'Dar Ben Abdellah', 'Djidiouia', 'Hamri', 'Ouled Sidi Mihoub', 'Mendes', 'Oued Essalem', 'Sidi Lazreg', 'Ammi Moussa', 'El Hassi', 'El Ouldja', 'Ain Tarek', 'Had Echkalla', 'Mazouna', 'El Guettar', 'Ouled Rhiou', 'Ouarizane', 'Yellel', 'Ain Rahma', 'Kalaa', 'Sidi Saada', 'Ramka', 'Lahlef', 'Beni Zentis', 'Souk El Had', 'Merdja Sidi Abed', 'Ouled Aiche', 'Sidi M\'Hamed Ben Ali', 'Mediouna'],

  // --- NEW WILAYAS (49 to 58) Created in 2019/2021 ---
  
  'Timimoun': [ // Was part of Adrar
    'Timimoun', 'Ouled Said', 'Metarfa', 'Talmine', 'Ouled Aissa', 'Charouine', 'Ksar Kaddour', 'Tinerkouk', 'Deldoul', 'Ouled Khoudir'
  ],
  'Bordj Badji Mokhtar': [ // Was part of Adrar
    'Bordj Badji Mokhtar', 'Timiaouine'
  ],
  'Ouled Djellal': [ // Was part of Biskra
    'Ouled Djellal', 'Sidi Khaled', 'Ras El Miaad', 'Besbes', 'Chaiba', 'Doucen'
  ],
  'Béni Abbès': [ // Was part of Béchar
    'Beni Abbes', 'Tamtert', 'Igli', 'El Ouata', 'Ouled Khoudir', 'Ksabi', 'Timoudi', 'Kerzaz', 'Beni Ikhlef', 'Tabelbala'
  ],
  'In Salah': [ // Was part of Tamanrasset
    'In Salah', 'Foggaret Ezzaouia', 'In Ghar'
  ],
  'In Guezzam': [ // Was part of Tamanrasset
    'In Guezzam', 'Tin Zaouatine'
  ],
  'Touggourt': [ // Was part of Ouargla
    'Touggourt', 'Nezla', 'Tebesbest', 'Zaouia El Abidia', 'Sidi Slimane', 'Temacine', 'Blidet Amor', 'Megarine', 'Mnagueur', 'Taibet', 'Benaceur', 'M\'Naguer', 'El Hadjira', 'El Allia'
  ],
  'Djanet': [ // Was part of Illizi
    'Djanet', 'Bordj El Haouas'
  ],
  'El M\'Ghair': [ // Was part of El Oued
    'El M\'Ghair', 'Oum Touyour', 'Sidi Khelil', 'Djamaa', 'M\'Rara', 'Sidi Amrane', 'Tenedla', 'El Meghaier'
  ],
  'El Meniaa': [ // Was part of Ghardaïa
    'El Meniaa', 'Hassi Gara', 'Hassi Fehal'
  ],
};