# Generated by Django 5.0.6 on 2026-02-13 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Promotion',
        ),
    ]
