# Generated by Django 5.0.6 on 2026-03-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_promotion_max_impressions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='audience_mode',
            field=models.CharField(choices=[('all', 'All'), ('followers', 'Followers'), ('nearby', 'Nearby'), ('wilaya', 'Wilaya'), ('custom', 'Custom Users')], default='all', max_length=20),
        ),
        migrations.AddField(
            model_name='promotion',
            name='clicks_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='promotion',
            name='impressions_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='promotion',
            name='kind',
            field=models.CharField(choices=[('promotion', 'Promotion'), ('advertising', 'Advertising')], default='promotion', max_length=20),
        ),
        migrations.AddField(
            model_name='promotion',
            name='placement',
            field=models.CharField(choices=[('home_top', 'Home Top'), ('home_feed', 'Home Feed'), ('search_top', 'Search Top')], default='home_top', max_length=20),
        ),
        migrations.AddField(
            model_name='promotion',
            name='priority_boost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='promotion',
            name='target_categories',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='promotion',
            name='target_user_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='promotion',
            name='target_wilayas',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
