# Generated by Django 5.0.6 on 2026-02-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_promotion_promotionimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='available_status',
            field=models.CharField(choices=[('available', 'Available'), ('out_of_stock', 'Out of Stock')], default='available', max_length=15),
        ),
        migrations.AddField(
            model_name='promotion',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
