# Generated by Django 5.0.6 on 2026-01-01 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_review_store_alter_review_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packproduct',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
