# Generated by Django 5.0.6 on 2026-02-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_pack_available_status_promotion_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hide_price',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pack',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
