# Generated by Django 5.0.6 on 2026-02-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_product_hide_price_pack_discount_max_digits'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='delivery_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pack',
            name='delivery_wilayas',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_wilayas',
            field=models.TextField(blank=True, default=''),
        ),
    ]
