# Generated by Django 5.0.6 on 2026-02-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_add_delivery_fields_to_product_and_pack'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon_code_point',
            field=models.IntegerField(blank=True, help_text='Material Icons codePoint, e.g. 59650 for Icons.restaurant', null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='icon_font_family',
            field=models.CharField(blank=True, default='MaterialIcons', max_length=100),
        ),
        migrations.AddField(
            model_name='category',
            name='icon_font_package',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
