# Generated by Django 5.0.6 on 2026-03-23 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_promotion_promotions_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreport',
            name='evidence_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='productreport',
            name='is_low_credibility',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productreport',
            name='reporter_reputation_score_at_submission',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productreport',
            name='scored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productreport',
            name='seriousness_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10),
        ),
        migrations.AddField(
            model_name='productreport',
            name='seriousness_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='credibility_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10),
        ),
        migrations.AddField(
            model_name='review',
            name='credibility_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='evidence_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='review',
            name='is_low_credibility',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='review',
            name='scored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
