# Generated by Django 5.0.6 on 2026-02-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_add_icon_fields_to_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='icon_code_point',
        ),
        migrations.RemoveField(
            model_name='category',
            name='icon_font_family',
        ),
        migrations.RemoveField(
            model_name='category',
            name='icon_font_package',
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, default='', help_text='MDI icon name, e.g. apple, carrot, smartphone', max_length=100),
        ),
    ]
