# Generated by Django 5.0.6 on 2026-02-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_simplify_category_icon_to_string'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
        migrations.AddField(
            model_name='category',
            name='icon_code_point',
            field=models.IntegerField(blank=True, help_text='Material Icons codePoint integer, e.g. 59447 for Icons.restaurant', null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='icon_font_family',
            field=models.CharField(blank=True, default='MaterialIcons', max_length=100),
        ),
        migrations.AddField(
            model_name='category',
            name='icon_font_package',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
