# Generated by Django 5.0.6 on 2026-02-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_revert_category_icon_to_codepoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon_code_point',
            field=models.CharField(blank=True, default='', help_text='Hex codePoint from fonts.google.com/icons, e.g. e027, e532', max_length=10),
        ),
    ]
