# Generated by Django 5.0.6 on 2026-02-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_icon_codepoint_hex_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='scarcity_level',
            field=models.IntegerField(default=5, help_text='1=Abundant (Bread), 10=Scarce (Cars)'),
        ),
    ]
