# Generated by Django 5.0.6 on 2026-03-15 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_subscriptionplan_plan_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPaymentProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='subscriptions/payment_proofs/')),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='subscriptions.subscriptionpaymentrequest')),
            ],
        ),
    ]
