# Generated by Django 5.0.6 on 2026-03-15 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_subscriptionpaymentproof'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionpaymentproof',
            name='description',
        ),
    ]
