# Generated by Django 5.0.6 on 2026-03-22 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_adcampaign_display_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adcampaign',
            name='display_hour',
        ),
    ]
