# Generated by Django 5.0.6 on 2026-03-07 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='max_impressions',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum unique viewers allowed for this promotion (null = unlimited).', null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='unique_viewers_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PromotionViewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewer_key', models.CharField(db_index=True, max_length=128)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewer_hits', to='catalog.promotion')),
            ],
            options={
                'unique_together': {('promotion', 'viewer_key')},
            },
        ),
    ]
