# Generated by Django 5.0.6 on 2026-03-15 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_promotion_age_geo_nullable_dates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='target_user_ids',
        ),
    ]
