# Generated by Django 5.0.6 on 2026-03-23 00:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_trustsettings_storereport_evidence_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trustsettings',
            name='analytics_retention_days',
            field=models.PositiveIntegerField(default=180),
        ),
        migrations.AddField(
            model_name='trustsettings',
            name='max_reports_per_day',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='trustsettings',
            name='report_cooldown_minutes',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='trustsettings',
            name='review_cooldown_minutes',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.CreateModel(
            name='AbuseFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(choices=[('report_spam', 'Report Spam'), ('low_cred_report', 'Low Credibility Report'), ('review_spam', 'Review Spam')], max_length=40)),
                ('target_type', models.CharField(choices=[('store', 'Store'), ('product', 'Product'), ('account', 'Account')], max_length=20)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('count', models.PositiveIntegerField(default=1)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abuse_flags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['actor', 'signal_type', 'target_type', 'target_id'], name='users_abuse_actor_i_fecceb_idx')],
            },
        ),
    ]
